### ISSUE TITLE
change license to MIT?

### ISSUE THREAD

**Issue by ixdy** [otiai10/curr#2]
Many of your other projects appear to use an MIT license, but at least some of them (such as mint or copy, indirectly through mint) depend on this project, which uses the WTFPL, which causes headaches for license-compliance checkers.

You changed mint from WTFPL to MIT [in the past](https://github.com/otiai10/mint/commit/fd1aaf1146c58772d4e047a5564c5771984c1914), so I hope you may be receptive to doing the same thing here.

Thanks!

**Comment by otiai10** [comment]
Completely makes sense. Thank you for pointing out.

**Comment by otiai10** [comment]
and tagged v1.0.0
